<?php
// Start output buffering to prevent any accidental output
ob_start();

require_once '../includes/init.php';
redirectIfNotLoggedIn();

// Include TCPDF library
require_once '../vendors/tcpdf/tcpdf.php';

// Check if it's a POST request
if ($_POST) {
    $start_date = $_POST['start_date'];
    $end_date = $_POST['end_date'];
    $format = $_POST['format'];
    $report_type = $_POST['report_type'] ?? 'sales';
    
    $database = new Database();
    $db = $database->getConnection();
    
    // Define report configurations
    $reports = [
'sales' => [
    'query' => "SELECT s.sale_date, p.name, p.sku, p.unit_type, s.qty, s.weight_kg, s.price, s.total, s.customer_name 
               FROM sales s 
               JOIN products p ON s.product_id = p.id 
               WHERE DATE(s.sale_date) BETWEEN ? AND ? 
               ORDER BY s.sale_date",
            'csv_filename' => "sales_report_" . date('Y-m-d') . ".csv",
            'pdf_filename' => "sales_report_" . date('Y-m-d') . ".pdf",
            'headers' => ['Date', 'Product', 'SKU', 'Quantity', 'Price', 'Total', 'Customer'],
            'title' => "SALES REPORT",
            'subtitle' => "From " . date('M j, Y', strtotime($start_date)) . " to " . date('M j, Y', strtotime($end_date))
        ],
        'products' => [
            'query' => "SELECT p.name, p.sku, p.category, p.cost_price, AVG(s.price) as avg_price,
                       SUM(s.qty) as total_sold, 
                       SUM(s.total) as revenue,
                       SUM(s.qty * p.cost_price) as cost_value,
                       SUM(s.total) - SUM(s.qty * p.cost_price) as gross_margin,
                       CASE 
                           WHEN SUM(s.total) > 0 
                           THEN ROUND((SUM(s.total) - SUM(s.qty * p.cost_price)) / SUM(s.total) * 100, 2)
                           ELSE 0
                       END as gross_margin_percent
                FROM sales s 
                JOIN products p ON s.product_id = p.id 
                WHERE DATE(s.sale_date) BETWEEN ? AND ? 
                GROUP BY p.id, p.name, p.sku, p.category, p.cost_price
                ORDER BY revenue DESC",
            'csv_filename' => "product_performance_" . date('Y-m-d') . ".csv",
            'pdf_filename' => "product_performance_" . date('Y-m-d') . ".pdf",
            'headers' => ['Product', 'SKU', 'Category', 'Unit Cost', 'Avg Price', 'Units Sold','Revenue', 'Cost Value',  'Gross Margin', 'Margin %'],
            'title' => "PRODUCT PERFORMANCE REPORT",
            'subtitle' => "From " . date('M j, Y', strtotime($start_date)) . " to " . date('M j, Y', strtotime($end_date))
        ],
        'inventory' => [
            'query' => "SELECT name, sku, category, stock_qty, reorder_level, cost_price, sale_price, 
                       (sale_price - cost_price) as unit_margin,
                       CASE 
                           WHEN sale_price > 0 
                           THEN ROUND((sale_price - cost_price) / sale_price * 100, 2)
                           ELSE 0
                       END as margin_percent,
                       (stock_qty * cost_price) as cost_value, 
                       (stock_qty * sale_price) as retail_value
                FROM products 
                ORDER BY stock_qty ASC, name",
            'csv_filename' => "inventory_status_" . date('Y-m-d') . ".csv",
            'pdf_filename' => "inventory_status_" . date('Y-m-d') . ".pdf",
            'headers' => ['Product', 'SKU', 'Cat.', 'Stk Qty', 'RO Lvl', 'Cost Price', 'Sale Price', 'Unit Margin', '% M', 'CV', 'Retail Value'],
            'title' => "INVENTORY STATUS REPORT",
            'subtitle' => "As of " . date('M j, Y')
        ]
    ];
    
    $config = $reports[$report_type];
    
    $stmt = $db->prepare($config['query']);
    
    if ($report_type === 'inventory') {
        $stmt->execute();
    } else {
        $stmt->execute([$start_date, $end_date]);
    }
    
    $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Clear any output that might have been generated
    ob_clean();
    
    if ($format == 'csv') {
        // Generate CSV with template
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="' . $config['csv_filename'] . '"');
        
        $output = fopen('php://output', 'w');
        
        // CSV Header Template
        fputcsv($output, ['INVENTORY SYSTEM - ' . $config['title']]);
        fputcsv($output, [$config['subtitle']]);
        fputcsv($output, ['Generated by: ' . $_SESSION['username']]);
        fputcsv($output, ['Generated on: ' . date('Y-m-d H:i:s')]);
        fputcsv($output, []); // Empty line
        
        // Add summary for sales report
        if ($report_type === 'sales' && count($data) > 0) {
            $total_revenue = array_sum(array_column($data, 'total'));
            $total_items = 0;
foreach ($data as $r) {
    if (($r['unit_type'] ?? '') === 'kg') {
        $total_items += (float)($r['weight_kg'] ?? 0);
    } else {
        $total_items += (float)($r['qty'] ?? 0);
    }
}
            
            fputcsv($output, ['SUMMARY:']);
            fputcsv($output, ['Total Sales:', count($data)]);
            fputcsv($output, ['Total Items Sold:', $total_items]);
            fputcsv($output, ['Total Revenue:', '₱' . number_format($total_revenue, 2)]);
            fputcsv($output, []); // Empty line
        }
        
        // Add summary for product performance report
        if ($report_type === 'products' && count($data) > 0) {
            $total_revenue = array_sum(array_column($data, 'revenue'));
            $total_cost = array_sum(array_column($data, 'cost_value'));
            $total_margin = array_sum(array_column($data, 'gross_margin'));
            $total_items = array_sum(array_column($data, 'total_sold'));
            
            fputcsv($output, ['SUMMARY:']);
            fputcsv($output, ['Total Units Sold:', $total_items]);
            fputcsv($output, ['Total Revenue:', '₱' . number_format($total_revenue, 2)]);
            fputcsv($output, ['Total Cost:', '₱' . number_format($total_cost, 2)]);
            fputcsv($output, ['Gross Margin:', '₱' . number_format($total_margin, 2)]);
            fputcsv($output, ['Overall Margin %:', ($total_revenue > 0 ? number_format(($total_margin / $total_revenue) * 100, 2) : '0.00') . '%']);
            fputcsv($output, []); // Empty line
        }
        
        // Add summary for inventory report
        if ($report_type === 'inventory' && count($data) > 0) {
            $total_cost_value = array_sum(array_column($data, 'cost_value'));
            $total_retail_value = array_sum(array_column($data, 'retail_value'));
            $total_stock_qty = array_sum(array_column($data, 'stock_qty'));
            $total_products = count($data);
            
            fputcsv($output, ['SUMMARY:']);
            fputcsv($output, ['Total Products:', $total_products]);
            fputcsv($output, ['Total Stock Qty:', $total_stock_qty]);
            fputcsv($output, ['Total Cost Value:', '₱' . number_format($total_cost_value, 2)]);
            fputcsv($output, ['Total Retail Value:', '₱' . number_format($total_retail_value, 2)]);
            fputcsv($output, ['Potential Gross Margin:', '₱' . number_format($total_retail_value - $total_cost_value, 2)]);
            fputcsv($output, []); // Empty line
        }
        
        // Column headers
        fputcsv($output, $config['headers']);
        
// Data rows
foreach ($data as $row) {
    $formatted_row = [];
    // Build row according to headers order
    foreach ($config['headers'] as $header) {
        $value = null;
        // Map header to database key or computed value
        switch ($header) {
            case 'Date':
                $value = $row['sale_date'] ?? '';
                break;
            case 'Product':
                $value = $row['name'] ?? '';
                break;
            case 'SKU':
                $value = $row['sku'] ?? '';
                break;
case 'Quantity':
case 'Qty':
case 'Stk Qty':
    if (isset($row['unit_type'])) {
        if ($row['unit_type'] == 'kg') {
            // For KG items: prefer weight_kg (actual sold weight), fallback to qty
            $kg = (isset($row['weight_kg']) && $row['weight_kg'] > 0)
                ? (float)$row['weight_kg']
                : (float)($row['qty'] ?? 0);

            $value = number_format($kg, 3) . ' kg';
        } else {
            $pcs = (float)($row['qty'] ?? $row['stock_qty'] ?? 0);
            $value = number_format($pcs) . ' pcs';
        }
    } else {
        $value = $row['qty'] ?? $row['stock_qty'] ?? 0;
    }
    break;
            case 'Price':
                $value = '₱' . number_format($row['price'] ?? 0, 2);
                break;
            case 'Total':
                $value = '₱' . number_format($row['total'] ?? 0, 2);
                break;
            case 'Customer':
                $value = $row['customer_name'] ?? '';
                break;
            case 'Unit Cost':
                $value = '₱' . number_format($row['cost_price'] ?? 0, 2);
                break;
            case 'Avg Price':
                $value = '₱' . number_format($row['avg_price'] ?? 0, 2);
                break;
            case 'Units Sold':
                if (isset($row['unit_type'])) {
                    if ($row['unit_type'] == 'kg') {
                        $value = number_format($row['total_sold'] ?? 0, 3) . ' kg';
                    } else {
                        $value = number_format($row['total_sold'] ?? 0) . ' pcs';
                    }
                } else {
                    $value = $row['total_sold'] ?? 0;
                }
                break;
            case 'Revenue':
                $value = '₱' . number_format($row['revenue'] ?? 0, 2);
                break;
            case 'Cost Value':
            case 'CV':
                $value = '₱' . number_format($row['cost_value'] ?? 0, 2);
                break;
            case 'Gross Margin':
                $value = '₱' . number_format($row['gross_margin'] ?? 0, 2);
                break;
            case 'Margin %':
            case '% M':
                $value = number_format($row['gross_margin_percent'] ?? $row['margin_percent'] ?? 0, 2) . '%';
                break;
            case 'Cat.':
                $value = $row['category'] ?? '';
                break;
            case 'RO Lvl':
                $value = $row['reorder_level'] ?? 0;
                break;
            case 'Cost Price':
                $value = '₱' . number_format($row['cost_price'] ?? 0, 2);
                break;
            case 'Sale Price':
                $value = '₱' . number_format($row['sale_price'] ?? 0, 2);
                break;
            case 'Unit Margin':
                $value = '₱' . number_format($row['unit_margin'] ?? 0, 2);
                break;
            case 'Retail Value':
                $value = '₱' . number_format($row['retail_value'] ?? 0, 2);
                break;
            default:
                $value = $row[$header] ?? '';
        }
        $formatted_row[] = $value;
    }
    fputcsv($output, $formatted_row);
}
        
        fclose($output);
        exit;
        
    } elseif ($format == 'pdf') {
        // Create new PDF document
        $pdf = new TCPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        
        // Set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Inventory System');
        $pdf->SetTitle($config['title']);
        $pdf->SetSubject($config['title']);
        
        // Remove default header/footer
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        
        // Set margins
        $pdf->SetMargins(10, 15, 10);
        $pdf->SetAutoPageBreak(TRUE, 15);
        
        // Add a page
        $pdf->AddPage();
        
        // Set font for title
        $pdf->SetFont('dejavusans', 'B', 16);
        
        // Title
        $pdf->Cell(0, 10, 'INVENTORY SYSTEM', 0, 1, 'C');
        $pdf->Cell(0, 10, $config['title'], 0, 1, 'C');
        $pdf->SetFont('dejavusans', '', 12);
        $pdf->Cell(0, 10, $config['subtitle'], 0, 1, 'C');
        
        // Add some space
        $pdf->Ln(5);
        
        // Company info
        $pdf->SetFont('dejavusans', '', 10);
        $pdf->Cell(0, 6, 'Generated by: ' . $_SESSION['username'], 0, 1);
        $pdf->Cell(0, 6, 'Generated on: ' . date('Y-m-d H:i:s'), 0, 1);
        $pdf->Ln(5);
        
        // Summary statistics for each report type
        if ($report_type === 'sales' && count($data) > 0) {
            $total_revenue = array_sum(array_column($data, 'total'));
            $total_items = 0;
foreach ($data as $r) {
    if (($r['unit_type'] ?? '') === 'kg') {
        $total_items += (float)($r['weight_kg'] ?? 0);
    } else {
        $total_items += (float)($r['qty'] ?? 0);
    }
}
            
            $pdf->SetFont('dejavusans', 'B', 12);
            $pdf->Cell(0, 8, 'SUMMARY:', 0, 1);
            $pdf->SetFont('dejavusans', '', 10);
            $pdf->Cell(0, 6, 'Total Sales: ' . count($data), 0, 1);
            $pdf->Cell(0, 6, 'Total Sold (pcs + kg): ' . number_format($total_items, 3), 0, 1);
            $pdf->Cell(0, 6, 'Total Revenue: ₱' . number_format($total_revenue, 2), 0, 1);
            $pdf->Ln(5);
        }
        
        // Summary for product performance report
        if ($report_type === 'products' && count($data) > 0) {
            $total_revenue = array_sum(array_column($data, 'revenue'));
            $total_cost = array_sum(array_column($data, 'cost_value'));
            $total_margin = array_sum(array_column($data, 'gross_margin'));
            $total_items = array_sum(array_column($data, 'total_sold'));
            $overall_margin_percent = $total_revenue > 0 ? ($total_margin / $total_revenue) * 100 : 0;
            
            $pdf->SetFont('dejavusans', 'B', 12);
            $pdf->Cell(0, 8, 'SUMMARY:', 0, 1);
            $pdf->SetFont('dejavusans', '', 10);
            $pdf->Cell(0, 6, 'Total Units Sold: ' . number_format($total_items), 0, 1);
            $pdf->Cell(0, 6, 'Total Revenue: ₱' . number_format($total_revenue, 2), 0, 1);
            $pdf->Cell(0, 6, 'Total Cost: ₱' . number_format($total_cost, 2), 0, 1);
            $pdf->Cell(0, 6, 'Gross Margin: ₱' . number_format($total_margin, 2), 0, 1);
            $pdf->Cell(0, 6, 'Overall Margin: ' . number_format($overall_margin_percent, 2) . '%', 0, 1);
            $pdf->Ln(5);
        }
        
        // Summary for inventory report
        if ($report_type === 'inventory' && count($data) > 0) {
            $total_cost_value = array_sum(array_column($data, 'cost_value'));
            $total_retail_value = array_sum(array_column($data, 'retail_value'));
            $total_stock_qty = array_sum(array_column($data, 'stock_qty'));
            $total_products = count($data);
            $potential_margin = $total_retail_value - $total_cost_value;
            $potential_margin_percent = $total_retail_value > 0 ? ($potential_margin / $total_retail_value) * 100 : 0;
            
            $pdf->SetFont('dejavusans', 'B', 12);
            $pdf->Cell(0, 8, 'SUMMARY:', 0, 1);
            $pdf->SetFont('dejavusans', '', 10);
            $pdf->Cell(0, 6, 'Total Products: ' . $total_products, 0, 1);
            $pdf->Cell(0, 6, 'Total Stock Qty: ' . number_format($total_stock_qty), 0, 1);
            $pdf->Cell(0, 6, 'Total Cost Value: ₱' . number_format($total_cost_value, 2), 0, 1);
            $pdf->Cell(0, 6, 'Total Retail Value: ₱' . number_format($total_retail_value, 2), 0, 1);
            $pdf->Cell(0, 6, 'Potential Gross Margin: ₱' . number_format($potential_margin, 2) . ' (' . number_format($potential_margin_percent, 2) . '%)', 0, 1);
            $pdf->Ln(5);
        }
        
        // Calculate column widths based on report type
        $col_widths = [];
        switch ($report_type) {
            case 'sales':
                // 7 columns
                $col_widths = [50, 100, 40, 20, 18, 22, 30];
                break;
            case 'products':
                // 10 columns - Adjusted widths for better fit
                $col_widths = [50, 35, 25, 25, 25, 25, 22, 24, 28, 22];
                break;
            case 'inventory':
                // 11 columns - Adjusted widths for better fit
                $col_widths = [49, 35, 18, 20, 20, 23, 23, 24, 18, 22, 25];
                break;
        }
        
        // Calculate total table width
        $table_width = array_sum($col_widths);
        
        // Get page width
        $page_width = $pdf->getPageWidth() - $pdf->getMargins()['left'] - $pdf->getMargins()['right'];
        
        // Center the table if it's smaller than page width
        if ($table_width < $page_width) {
            $pdf->SetX(($page_width - $table_width) / 2 + $pdf->getMargins()['left']);
        }
        
        // Store current X position for rows
        $start_x = $pdf->GetX();
        
        // Header row with background
        $pdf->SetFont('dejavusans', 'B', 9);
        $pdf->SetFillColor(220, 220, 220);
        foreach ($config['headers'] as $index => $header) {
            $pdf->Cell($col_widths[$index], 7, $header, 1, 0, 'C', true);
        }
        $pdf->Ln();
        
// Data rows
$pdf->SetFont('dejavusans', '', 8);
$fill = false;

foreach ($data as $row) {
    // Check if we need a new page
    if ($pdf->GetY() > $pdf->getPageHeight() - 40) {
        $pdf->AddPage();
        if ($table_width < $page_width) {
            $pdf->SetX(($page_width - $table_width) / 2 + $pdf->getMargins()['left']);
        } else {
            $pdf->SetX($start_x);
        }
        // Redraw header
        $pdf->SetFont('dejavusans', 'B', 9);
        $pdf->SetFillColor(220, 220, 220);
        foreach ($config['headers'] as $index => $header) {
            $pdf->Cell($col_widths[$index], 7, $header, 1, 0, 'C', true);
        }
        $pdf->Ln();
        $pdf->SetFont('dejavusans', '', 8);
        $fill = false;
    }
    
    // Build display row based on headers
    $display_row = [];
    foreach ($config['headers'] as $header) {
        $value = '';
        switch ($header) {
            case 'Date':
                $value = $row['sale_date'] ?? '';
                break;
            case 'Product':
                $value = $row['name'] ?? '';
                break;
            case 'SKU':
                $value = $row['sku'] ?? '';
                break;
case 'Quantity':
case 'Qty':
case 'Stk Qty':
    if (isset($row['unit_type'])) {
        if ($row['unit_type'] == 'kg') {
            // Prefer actual sold weight (weight_kg). Fallback to qty if not present.
            $kg = (isset($row['weight_kg']) && (float)$row['weight_kg'] > 0)
                ? (float)$row['weight_kg']
                : (float)($row['qty'] ?? 0);

            $value = number_format($kg, 3) . ' kg';
        } else {
            $pcs = (float)($row['qty'] ?? 0);
            $value = number_format($pcs) . ' pcs';
        }
    } else {
        $value = $row['qty'] ?? $row['stock_qty'] ?? 0;
    }
    break;
            case 'Price':
                $value = '₱' . number_format($row['price'] ?? 0, 2);
                break;
            case 'Total':
                $value = '₱' . number_format($row['total'] ?? 0, 2);
                break;
            case 'Customer':
                $value = $row['customer_name'] ?? '';
                break;
            case 'Unit Cost':
                $value = '₱' . number_format($row['cost_price'] ?? 0, 2);
                break;
            case 'Avg Price':
                $value = '₱' . number_format($row['avg_price'] ?? 0, 2);
                break;
            case 'Units Sold':
                if (isset($row['unit_type'])) {
                    if ($row['unit_type'] == 'kg') {
                        $value = number_format($row['total_sold'] ?? 0, 3) . ' kg';
                    } else {
                        $value = number_format($row['total_sold'] ?? 0) . ' pcs';
                    }
                } else {
                    $value = $row['total_sold'] ?? 0;
                }
                break;
            case 'Revenue':
                $value = '₱' . number_format($row['revenue'] ?? 0, 2);
                break;
            case 'Cost Value':
            case 'CV':
                $value = '₱' . number_format($row['cost_value'] ?? 0, 2);
                break;
            case 'Gross Margin':
                $value = '₱' . number_format($row['gross_margin'] ?? 0, 2);
                break;
            case 'Margin %':
            case '% M':
                $value = number_format($row['gross_margin_percent'] ?? $row['margin_percent'] ?? 0, 2) . '%';
                break;
            case 'Cat.':
                $value = $row['category'] ?? '';
                break;
            case 'RO Lvl':
                $value = $row['reorder_level'] ?? 0;
                break;
            case 'Cost Price':
                $value = '₱' . number_format($row['cost_price'] ?? 0, 2);
                break;
            case 'Sale Price':
                $value = '₱' . number_format($row['sale_price'] ?? 0, 2);
                break;
            case 'Unit Margin':
                $value = '₱' . number_format($row['unit_margin'] ?? 0, 2);
                break;
            case 'Retail Value':
                $value = '₱' . number_format($row['retail_value'] ?? 0, 2);
                break;
            default:
                $value = $row[$header] ?? '';
        }
        $display_row[] = $value;
    }
    
    // Set fill color
    if ($fill) {
        $pdf->SetFillColor(245, 245, 245);
    } else {
        $pdf->SetFillColor(255, 255, 255);
    }
    
    // Draw cells
    foreach ($display_row as $index => $cell_value) {
        // Truncate long text
        if (strlen($cell_value) > 30) {
            $cell_value = substr($cell_value, 0, 27) . '...';
        }
        
        // Determine alignment
        $align = 'L';
        $current_header = $config['headers'][$index] ?? '';
        if (in_array($current_header, ['Quantity', 'Qty', 'Stk Qty', 'RO Lvl', 'Units Sold', 'Unit Cost', 'Avg Price', 'Cost Price', 'Sale Price', 'Unit Margin', 'CV', 'Revenue', 'Gross Margin', 'Retail Value'])) {
            $align = 'R';
        } elseif (in_array($current_header, ['% M', 'Margin %'])) {
            $align = 'C';
        }
        
        $pdf->Cell($col_widths[$index], 6, $cell_value, 1, 0, $align, $fill);
    }
    $pdf->Ln();
    $fill = !$fill;
}
        
        // If no data
        if (count($data) === 0) {
            // Reset position to center
            if ($table_width < $page_width) {
                $pdf->SetX(($page_width - $table_width) / 2 + $pdf->getMargins()['left']);
            } else {
                $pdf->SetX($start_x);
            }
            $pdf->Cell($table_width, 20, 'No data found for the selected period', 1, 1, 'C');
        }
        
        // REMOVED: Automatic page numbering that was causing extra pages
        // Instead, we'll manually add page numbers only when we have multiple pages
        
        // Get the current page number
        $current_page = $pdf->getPage();
        
        // Only add page number if we're on the last page and have more than 1 page
        if ($current_page > 1) {
            // Go to the last page and add page number
            for ($page = 1; $page <= $current_page; $page++) {
                $pdf->setPage($page);
                $pdf->SetY(-15);
                $pdf->SetFont('dejavusans', 'I', 8);
                $pdf->Cell(0, 10, "Page $page of $current_page", 0, 0, 'C');
            }
        }
        
        // Close and output PDF document
        $pdf->Output($config['pdf_filename'], 'D');
        exit;
    }
} else {
    // If not POST request, redirect back
    header('Location: ../pages/dashboard.php');
    exit;
}
?>